spring:
  application:
    name: devsidekick

gemini:
  liveMode: ${GEMINI_LIVE_MODE:false}
  model: ${GEMINI_MODEL:gemini-1.5-pro-latest}
  apiKey: ${GEMINI_API_KEY}

google-docs:
  liveMode: ${GOOGLE_DOCS_LIVE_MODE:false}
  applicationName: ${GOOGLE_DOCS_APP:Google Docs API}
  brDocUrl: ${BR_DOC_URL:https://docs.google.com/document/d/1jATNcwr1hq8IOUgqTd2StJc8RPM-MZHNEERZRMGK9og}

project:
  formattedName: ${FORMATTED_PROJECT_NAME:Coffee Shop}
  historyFrom: ${HISTORY_FROM:07/23/2024}
  historyTo: ${HISTORY_TO:07/23/2024}

github:
  repositoryName: ${GITHUB_REPO_NAME:coffeeshop}
  repositoryOwner: ${GITHUB_REPO_OWNER:AnnaHrunova}
  accessToken: ${GITHUB_ACCESS_TOKEN}

