spring:
  application:
    name: devsidekick

gemini:
  liveMode: ${GEMINI_LIVE_MODE:false}
  apiKey: ${GEMINI_API_KEY}

project:
  formattedName: ${FORMATTED_PROJECT_NAME:Coffee Shop}
  brDocId: ${BR_DOC_ID:1jATNcwr1hq8IOUgqTd2StJc8RPM-MZHNEERZRMGK9og}
  historyFrom: ${HISTORY_FROM:07/25/2024}
  historyTo: ${HISTORY_TO:07/25/2024}

github:
  repositoryName: ${GITHUB_REPO_NAME:coffeeshop}
  repositoryOwner: ${GITHUB_REPO_OWNER:AnnaHrunova}
  accessToken: ${GITHUB_ACCESS_TOKEN}

